In [27]:
import seaborn as sns
import numpy as np
import matplotlib as plt
import pandas as pd

In [29]:
df = pd.read_csv("insurance_data.csv")


In [31]:
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [33]:
df.tail()

age  bought_insurance
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [35]:
df.describe()

age  bought_insurance
count  27.000000         27.000000
mean   39.666667          0.518519
std    15.745573          0.509175
min    18.000000          0.000000
25%    25.000000          0.000000
50%    45.000000          1.000000
75%    54.500000          1.000000
max    62.000000          1.000000

In [37]:
df.info

<bound method DataFrame.info of     age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0>

In [39]:
df.isnull().sum()

age                 0
bought_insurance    0
dtype: int64

In [45]:
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)

In [47]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [49]:
model.fit(X_train, y_train)

LogisticRegression()

In [51]:
y_predicted = model.predict(X_test)

In [53]:
model.score(X_test,y_test)

0.8333333333333334

In [55]:
y_predicted

array([1, 1, 1, 0, 1, 0], dtype=int64)

In [57]:
model.coef_

array([[0.14335344]])

In [59]:
model.intercept_

array([-5.36663392])

In [63]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [67]:
def prediction_function(age):
    z = 0.042 * age - 1.53 # 0.04150133 ~ 0.042 and -1.52726963 ~ -1.53
    y = sigmoid(z)
    return y

In [69]:
age = 35
prediction_function(age)

0.4850044983805899

In [71]:
age = 43
prediction_function(age)

0.568565299077705